#pragma once

#include <stdint.h>
#include <i2c_fifo.h>
#include <i2c_slave.h>
#include <pico/stdlib.h>

void setup_i2c_peripheral(i2c_inst_t *i2c, uint8_t sda_pin, uint8_t scl_pin, uint8_t address, uint32_t baudrate, i2c_slave_handler_t handler);

void setup_i2c_registers();

void i2c_slave_handler(i2c_inst_t *i2c, i2c_slave_event_t event);
void i2c_task();

void i2c_register_write(uint8_t reg, uint8_t value);

void i2c_usb_set_mounted(bool mounted);
void i2c_usb_set_suspended(bool suspended, bool remote_wakeup_en);

enum {
    // 0-7
    I2C_REGISTER_FW_VER,
    I2C_REGISTER_GPIO_DIR,
    I2C_REGISTER_GPIO_IN,
    I2C_REGISTER_GPIO_OUT,
    I2C_REGISTER_LCD_BACKLIGHT,
    I2C_REGISTER_FPGA,
    I2C_REGISTER_INPUT1,
    I2C_REGISTER_INPUT2,

    // 8-15
    I2C_REGISTER_INTERRUPT1,
    I2C_REGISTER_INTERRUPT2,
    I2C_REGISTER_ADC_TRIGGER,
    I2C_REGISTER_ADC_VALUE_VUSB_LO,
    I2C_REGISTER_ADC_VALUE_VUSB_HI,
    I2C_REGISTER_ADC_VALUE_VBAT_LO,
    I2C_REGISTER_ADC_VALUE_VBAT_HI,
    I2C_REGISTER_USB,

    // 16-23
    I2C_REGISTER_BL_TRIGGER,
    I2C_REGISTER_RESERVED0,
    I2C_REGISTER_RESERVED1,
    I2C_REGISTER_RESERVED2,
    I2C_REGISTER_RESERVED3,
    I2C_REGISTER_RESERVED4,
    I2C_REGISTER_RESERVED5,
    I2C_REGISTER_RESERVED6,

    // 24-31
    I2C_REGISTER_UID0, // Unique board identifier of the RP2040
    I2C_REGISTER_UID1,
    I2C_REGISTER_UID2,
    I2C_REGISTER_UID3,
    I2C_REGISTER_UID4,
    I2C_REGISTER_UID5,
    I2C_REGISTER_UID6,
    I2C_REGISTER_UID7,

    // 32-39
    I2C_REGISTER_SCRATCH0, // Used by the ESP32 to store boot parameters, can also be read and written to from WebUSB
    I2C_REGISTER_SCRATCH1,
    I2C_REGISTER_SCRATCH2,
    I2C_REGISTER_SCRATCH3,
    I2C_REGISTER_SCRATCH4,
    I2C_REGISTER_SCRATCH5,
    I2C_REGISTER_SCRATCH6,
    I2C_REGISTER_SCRATCH7,

    // 40-47
    I2C_REGISTER_SCRATCH8, // Used by the ESP32 to store boot parameters, can also be read and written to from WebUSB
    I2C_REGISTER_SCRATCH9,
    I2C_REGISTER_SCRATCH10,
    I2C_REGISTER_SCRATCH11,
    I2C_REGISTER_SCRATCH12,
    I2C_REGISTER_SCRATCH13,
    I2C_REGISTER_SCRATCH14,
    I2C_REGISTER_SCRATCH15,

    // 48-55
    I2C_REGISTER_SCRATCH16, // Used by the ESP32 to store boot parameters, can also be read and written to from WebUSB
    I2C_REGISTER_SCRATCH17,
    I2C_REGISTER_SCRATCH18,
    I2C_REGISTER_SCRATCH19,
    I2C_REGISTER_SCRATCH20,
    I2C_REGISTER_SCRATCH21,
    I2C_REGISTER_SCRATCH22,
    I2C_REGISTER_SCRATCH23,

    // 56-63
    I2C_REGISTER_SCRATCH24, // Used by the ESP32 to store boot parameters, can also be read and written to from WebUSB
    I2C_REGISTER_SCRATCH25,
    I2C_REGISTER_SCRATCH26,
    I2C_REGISTER_SCRATCH27,
    I2C_REGISTER_SCRATCH28,
    I2C_REGISTER_SCRATCH29,
    I2C_REGISTER_SCRATCH30,
    I2C_REGISTER_SCRATCH31,

    // 64-71
    I2C_REGISTER_SCRATCH32, // Used by the ESP32 to store boot parameters, can also be read and written to from WebUSB
    I2C_REGISTER_SCRATCH33,
    I2C_REGISTER_SCRATCH34,
    I2C_REGISTER_SCRATCH35,
    I2C_REGISTER_SCRATCH36,
    I2C_REGISTER_SCRATCH37,
    I2C_REGISTER_SCRATCH38,
    I2C_REGISTER_SCRATCH39,

    // 72-79
    I2C_REGISTER_SCRATCH40, // Used by the ESP32 to store boot parameters, can also be read and written to from WebUSB
    I2C_REGISTER_SCRATCH41,
    I2C_REGISTER_SCRATCH42,
    I2C_REGISTER_SCRATCH43,
    I2C_REGISTER_SCRATCH44,
    I2C_REGISTER_SCRATCH45,
    I2C_REGISTER_SCRATCH46,
    I2C_REGISTER_SCRATCH47,

    // 80-87
    I2C_REGISTER_SCRATCH48, // Used by the ESP32 to store boot parameters, can also be read and written to from WebUSB
    I2C_REGISTER_SCRATCH49,
    I2C_REGISTER_SCRATCH50,
    I2C_REGISTER_SCRATCH51,
    I2C_REGISTER_SCRATCH52,
    I2C_REGISTER_SCRATCH53,
    I2C_REGISTER_SCRATCH54,
    I2C_REGISTER_SCRATCH55,

    // 88-95
    I2C_REGISTER_SCRATCH56, // Used by the ESP32 to store boot parameters, can also be read and written to from WebUSB
    I2C_REGISTER_SCRATCH57,
    I2C_REGISTER_SCRATCH58,
    I2C_REGISTER_SCRATCH59,
    I2C_REGISTER_SCRATCH60,
    I2C_REGISTER_SCRATCH61,
    I2C_REGISTER_SCRATCH62,
    I2C_REGISTER_SCRATCH63,

    // 96-103
    I2C_REGISTER_RESERVED7,
    I2C_REGISTER_RESERVED8,
    I2C_REGISTER_RESERVED9,
    I2C_REGISTER_RESERVED10,
    I2C_REGISTER_RESERVED11,
    I2C_REGISTER_RESERVED12,
    I2C_REGISTER_RESERVED13,
    I2C_REGISTER_RESERVED14,

    // 104-111
    I2C_REGISTER_RESERVED15,
    I2C_REGISTER_RESERVED16,
    I2C_REGISTER_RESERVED17,
    I2C_REGISTER_RESERVED18,
    I2C_REGISTER_RESERVED19,
    I2C_REGISTER_RESERVED20,
    I2C_REGISTER_RESERVED21,
    I2C_REGISTER_RESERVED22,

    // 112-119
    I2C_REGISTER_RESERVED23,
    I2C_REGISTER_RESERVED24,
    I2C_REGISTER_RESERVED25,
    I2C_REGISTER_RESERVED26,
    I2C_REGISTER_RESERVED27,
    I2C_REGISTER_RESERVED28,
    I2C_REGISTER_RESERVED29,
    I2C_REGISTER_RESERVED30,

    // 120-127
    I2C_REGISTER_RESERVED31,
    I2C_REGISTER_RESERVED32,
    I2C_REGISTER_RESERVED33,
    I2C_REGISTER_RESERVED34,
    I2C_REGISTER_RESERVED35,
    I2C_REGISTER_RESERVED36,
    I2C_REGISTER_RESERVED37,
    I2C_REGISTER_RESERVED38,

    // ... (128-255)
};
