#pragma once

#include <stdint.h>

enum { REPORT_ID_KEYBOARD = 1, REPORT_ID_MOUSE, REPORT_ID_CONSUMER_CONTROL, REPORT_ID_GAMEPAD, REPORT_ID_COUNT };

enum { VENDOR_REQUEST_WEBUSB = 1, VENDOR_REQUEST_MICROSOFT = 2 };

enum { ITF_NUM_CDC_0, ITF_NUM_CDC_0_DATA, ITF_NUM_CDC_1, ITF_NUM_CDC_1_DATA, ITF_NUM_VENDOR_0, ITF_NUM_VENDOR_1, ITF_NUM_TOTAL };

extern uint8_t const desc_ms_os_20[];
